### ISSUE TITLE
Non-deterministic behavior of Tree.fit

### ISSUE THREAD

**Issue by AVBelyy** [navefr/ExKMC#3]
Hi,

By default, the `fit` method of `ExKMC.Tree.Tree` is non-deterministic when `kmeans=None`, because in that case `kmeans` is initialized without providing `random_state`:
```python
if kmeans is None:
    if self.verbose > 0:
        print('Finding %d-means' % self.k)
    kmeans = KMeans(self.k, n_jobs=self.n_jobs, verbose=self.verbose, n_init=1, max_iter=40)  # Note: no `random_state`
    kmeans.fit(x_data)
```

Perhaps it makes sense to add `random_state=None` as an additional parameter to `ExKMC.Tree.Tree.fit`, or modify an example usage in README.md to pass an external `kmeans` instance (initialized with say `random_state=42`) to make it slightly less confusing?

**Comment by navefr** [comment]
Hi Anton,

I appreciate the suggestion, thank you!

In commit #[13200f938effd14039c8237da16a49e2b8f12594](https://github.com/navefr/ExKMC/commit/13200f938effd14039c8237da16a49e2b8f12594) I added an option for deterministic fit.
The optional parameter `random_state=None`  is part of the Tree constructor. 
I preferred to add the parameter to the constructor (instead of `ExKMC.Tree.Tree.fit`) to make it more aligned with `sklearn`  design style.
